"""empty message

Revision ID: 1eafb21d0e39
Revises: 4e6327f1dbb9
Create Date: 2023-11-22 13:02:09.496452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eafb21d0e39'
down_revision = '4e6327f1dbb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), nullable=True),
    sa.Column('goods_service_id', sa.INTEGER(), nullable=True),
    sa.Column('store_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['goods_service_id'], ['goods_services.id'], name='fk_cart_goods_service_id_goods_services'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='fk_cart_store_id_stores'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name='fk_cart_transaction_id_transactions'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
