"""empty message

Revision ID: 3d01abaf6f67
Revises: c957df9463d2
Create Date: 2023-11-18 22:59:06.573866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d01abaf6f67'
down_revision = 'c957df9463d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_subscriptions_client_id_clients')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_subscriptions_store_id_stores'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
