"""empty message

Revision ID: 4e6327f1dbb9
Revises: a16612446583
Create Date: 2023-11-22 12:54:38.779084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e6327f1dbb9'
down_revision = 'a16612446583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('goods_service_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goods_service_id'], ['goods_services.id'], name=op.f('fk_cart_goods_service_id_goods_services')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_cart_store_id_stores')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_cart_transaction_id_transactions')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###
