"""empty message

Revision ID: eaa4c225e7db
Revises: edbc932d8b2a
Create Date: 2023-11-27 22:55:26.924370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa4c225e7db'
down_revision = 'edbc932d8b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goods_service_names', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('goods_service_names')

    # ### end Alembic commands ###
